### ISSUE TITLE
fix inotify memory leak

### ISSUE THREAD

**Issue by sleexyz** [sleexyz/hylogen#22]

**Comment by sleexyz** [comment]
Also inotify doesn't work on OSX...

**Comment by vivid-synth** [comment]
What's the memory leak?

**Comment by sleexyz** [comment]
If `hylogen` runs for a while it accrues inotify handlers and when a file changes, it ends up running the callback multiple times. After a while I'll have so many inotify handlers that ghc comes to a halt

**Comment by sleexyz** [comment]
fixed with f14e334f233200fc960e6e49aa2f6d668743696d
