### ISSUE TITLE
more documentation!!

### ISSUE THREAD

**Issue by evancasey** [sleexyz/hylogen#23]

**Comment by evancasey** [comment]
[![selfie-0](http://i.imgur.com/2ZdsRZ7.png)](https://github.com/thieman/github-selfies/)

**Comment by evancasey** [comment]
[![selfie-0](http://i.imgur.com/l7LHGN6.png)](https://github.com/thieman/github-selfies/)

**Comment by sleexyz** [comment]
duplicate of #5 .

_let these photos be hidden away in depths of the githubs..._
